### ISSUE TITLE
No updates for samueltardieu/octopush-akka

### ISSUE THREAD

**Issue by samueltardieu** [scala-steward-org/scala-steward#1957]
The repository [`samueltardieu/octopush-akka`](https://github.com/samueltardieu/octopush-akka) does not seem to receive any PR from scala-steward, while the other `samueltardieu/*` repositories do regularly. Is there anything blocking the analysis for this particular repository? Should I change something? I couldn't find anything specific in the documentation. 

For example, my other repositories just received a PR to migrate to Akka 2.6.13 while this particular one didn't.

Maybe a FAQ entry could explain how to locally run scala-steward and see how it understand things.

**Comment by fthomas** [comment]
From the logs:
```
2021-02-23 21:02:19,789 INFO  Process update com.typesafe.akka:{(akka-actor, akka-actor_2.13), (akka-stream, akka-stream_2.13), (akka-stream-testkit, akka-stream-testkit_2.13)} : 2.6.10 -> 2.6.13
2021-02-23 21:02:19,948 INFO  Trying heuristic 'moduleId'
2021-02-23 21:02:19,953 INFO  Create branch update/akka-actor-2.6.13
2021-02-23 21:02:20,428 INFO  Push 1 commit(s)
2021-02-23 21:02:23,629 ERROR Steward samueltardieu/octopush-akka failed
java.io.IOException: 'git push --force --set-upstream origin update/akka-actor-2.6.13' exited with code 1
To https://github.com/scala-steward/octopush-akka.git
 ! [remote rejected] update/akka-actor-2.6.13 -> update/akka-actor-2.6.13 (cannot lock ref 'refs/heads/update/akka-actor-2.6.13':
 'refs/heads/update' exists; cannot create 'refs/heads/update/akka-actor-2.6.13')
error: failed to push some refs to 'https://scala-steward@github.com/scala-steward/octopush-akka.git'
```
It looks to me that we're hitting #741 here.

**Comment by samueltardieu** [comment]
Thanks @fthomas. I removed the `update` branch on my repository. If I understand #741 correctly, it should not have been imported into the scala-steward clone now that #741 is fixed. Could you rerun (if needed) scala-steward so that it now pushed the PR?

**Comment by samueltardieu** [comment]
(and maybe include a FAQ entry if  removing the `update` branch is enough and does not require a manual intervention on your side, so that people like me can handle this themselves in the future)

**Comment by fthomas** [comment]
#741 is not fixed and @scala-steward's fork still has that branch: https://github.com/scala-steward/octopush-akka/tree/update

**Comment by samueltardieu** [comment]
Who can remove the branch? Issues are disabled in @scala-steward 's fork.

**Comment by fthomas** [comment]
I deleted the branch via `git push https://scala-steward@github.com/scala-steward/octopush-akka.git :update`. You should receive updates soon.

**Comment by samueltardieu** [comment]
Thanks @fthomas!
